django_artistportfolio/urls.py
from django.conf.urls.defaults import patterns, url
from views import IndexView, SeriesView

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view()),
    url(r'^(?P<slug>[\w-]+)/$', SeriesView.as_view(), name='single_series'),
)

django_artistportfolio/models.py
from django.db import models
from feincms.content.application import models as app_models
from feincms.module.medialibrary.models import MediaFile
from jsonfield import JSONField

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    position = models.IntegerField()

    def save(self, *args, **kwargs):
        model = self.__class__

        if self.position is None:
            # Append
            try:
                last = model.objects.order_by('-position')[0]
                self.position = last.position + 1
            except IndexError:
                # First row
                self.position = 0

        return super(Category, self).save(*args, **kwargs)

    class Meta:
        ordering = ['position']

    def __unicode__(self):
        return '%s' % (self.name)

class VimeoMeta(models.Model):
    vimeo_id = models.IntegerField()
    data = JSONField()

    @property
    def iframe(self):
        template = '<iframe src="http://player.vimeo.com/video/%s?title=0&byline=0&portrait=0" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>'
        return template % (self.vimeo_id)

class Series(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category)
    is_active = models.BooleanField()

    description = models.TextField(blank=True)
    behind_the_scenes = models.URLField(blank=True, help_text="Vimeo url to behind the scenes footage")
    vimeo_meta = models.ForeignKey(VimeoMeta, blank=True, null=True)

    def __unicode__(self):
        return '%s' % (self.name)

    @app_models.permalink
    def get_absolute_url(self):
        return ('single_series', 'django_artistportfolio.urls', (), {'slug':self.slug})

    @property
    def first_thumbnail(self):
        media = self.media_set.all()[:1]
        if media:
            return media[0].thumbnail.file.url

class CreditName(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return '%s' % (self.name)

class Credit(models.Model):
    series = models.ForeignKey(Series)
    name = models.ForeignKey(CreditName)
    value = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name.name

class Media(models.Model):
    series = models.ForeignKey(Series)
    thumbnail = models.ForeignKey(MediaFile, blank=True, null=True, related_name='thumbnail_set')
    normal = models.ForeignKey(MediaFile, blank=True, null=True, related_name='normal_set')
    zoomed = models.ForeignKey(MediaFile, blank=True, null=True, related_name='zoomed_set')

class Cinema(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    video = models.URLField(blank=True, help_text="Vimeo url")
    vimeo_meta = models.ForeignKey(VimeoMeta, blank=True, null=True)

from listeners import *

django_artistportfolio/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.conf import settings
from models import Series

class IndexView(TemplateView):
    template_name = 'portfolio/index.html'

    def get_context_data(self, **kwargs):
        return {'all_series': Series.objects.filter(is_active=True)}

    def render_to_response(self, context, **response_kwargs):
        if 'app_config' in getattr(self.request, '_feincms_extra_context', {}):
            return self.get_template_names(), context

        return super(IndexView, self).render_to_response(context, **response_kwargs)


class SeriesView(TemplateView):
    template_name = 'portfolio/series.html'

    def get_context_data(self, **kwargs):
        series = get_object_or_404(Series, slug=kwargs['slug'], is_active=True)
        return {'series':series}

    def render_to_response(self, context, **response_kwargs):
        if 'app_config' in getattr(self.request, '_feincms_extra_context', {}):
            return self.get_template_names(), context

        return super(ConcertView, self).render_to_response(context, **response_kwargs)

django_artistportfolio/templates/portfolio/base.html
{% extends feincms_page.template.path|default:"base.html" %}

{% block body_class %}portfolio-page{% endblock %}

{% block content %}
    {% block portfolio_content %}{% endblock %}
{% endblock %}

django_artistportfolio/templates/portfolio/index.html
{% extends "portfolio/base.html" %}


{% block portfolio_content %}
	<ul class="media-list">
		{% for series in all_series %}
		<li class="media">
			<a class="pull-left" href="{{series.get_absolute_url}}">
				<img class="media-object" src="{{series.first_thumbnail}}">
			</a>
			<div class="media-body">
				<h3 class="media-heading">{{series.name}}
					<small>in {{series.category.name}}</small></h3>
			</div>
		</li>
		{% endfor %}
	</ul>
{% endblock %}

django_artistportfolio/templates/portfolio/series.html
{% extends "portfolio/base.html" %}

{% block content_title %}
    <h2><a href="{{feincms_page.get_absolute_url}}">{{feincms_page.page_title}}</a></h2>
    <h1>
        {{series.name}}
		<small>in {{series.category.name}}</small>
    </h1>
{% endblock %}

{% block portfolio_content %}

	<div class="row">
		<div class="span9">
			<ul class="unstyled">
			{% for media in series.media_set.all %}
				<li><img src="{{media.normal.file.url}}"><br><br></li>
			{% endfor %}
			</ul>
		</div>
		<div class="span3">
			{{series.description}}
			<dl>
				{% for credit in series.credit_set.all %}
					<dt>{{credit}}</dt>
						<dd>{{credit.value}}</dd>
				{% endfor %}
			</dl>
		</div>

	</div>

{% endblock %}